CREATE TABLE [dbo].[T_PRESTAMOS]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
	[Fecha] DATETIME NOT NULL, 
	[Id_Elemento] BIGINT NOT NULL, 
	[Id_Persona] BIGINT NOT NULL, 
	CONSTRAINT [FK_T_PRESTAMOS_T_PERSONAS] FOREIGN KEY (Id_Persona) REFERENCES T_PERSONAS(Id),
	CONSTRAINT [FK_T_PRESTAMOS_T_ELEMENTOS] FOREIGN KEY (Id_Elemento) REFERENCES T_ELEMENTOS(Id)
	
)
